insert into regije (regije) values ('Tunisia');
insert into regije (regije) values ('Portugal');
insert into regije (regije) values ('India');
insert into regije (regije) values ('Palestinian Territory');
insert into regije (regije) values ('Malaysia');
insert into regije (regije) values ('Kenya');
insert into regije (regije) values ('Poland');
insert into regije (regije) values ('Canada');
insert into regije (regije) values ('China');
insert into regije (regije) values ('China');
insert into regije (regije) values ('Indonesia');
insert into regije (regije) values ('Brazil');
insert into regije (regije) values ('China');
insert into regije (regije) values ('Indonesia');
insert into regije (regije) values ('Iran');
insert into regije (regije) values ('Brazil');
insert into regije (regije) values ('Thailand');
insert into regije (regije) values ('Azerbaijan');
insert into regije (regije) values ('Indonesia');
insert into regije (regije) values ('Malaysia');
insert into regije (regije) values ('Indonesia');
insert into regije (regije) values ('Madagascar');
insert into regije (regije) values ('Colombia');
insert into regije (regije) values ('China');
insert into regije (regije) values ('Colombia');
insert into regije (regije) values ('Czech Republic');
insert into regije (regije) values ('Honduras');