insert into regije (regije) values ('Philippines');
insert into regije (regije) values ('China');
insert into regije (regije) values ('Syria');
insert into regije (regije) values ('Mexico');
insert into regije (regije) values ('Mongolia');
insert into regije (regije) values ('China');
insert into regije (regije) values ('Mongolia');
insert into regije (regije) values ('Indonesia');
insert into regije (regije) values ('United States');
insert into regije (regije) values ('United States');
insert into regije (regije) values ('Argentina');
insert into regije (regije) values ('Thailand');
insert into regije (regije) values ('Peru');
insert into regije (regije) values ('Russia');
insert into regije (regije) values ('Indonesia');
insert into regije (regije) values ('Hungary');
insert into regije (regije) values ('Brazil');
insert into regije (regije) values ('Indonesia');
insert into regije (regije) values ('Philippines');
insert into regije (regije) values ('Russia');
