insert into regije (regija) values ('Poland');
insert into regije (regija) values ('Madagascar');
insert into regije (regija) values ('Poland');
insert into regije (regija) values ('Indonesia');
insert into regije (regija) values ('Norway');
insert into regije (regija) values ('Philippines');
insert into regije (regija) values ('Malaysia');
insert into regije (regija) values ('Japan');
insert into regije (regija) values ('Poland');
insert into regije (regija) values ('Indonesia');
insert into regije (regija) values ('Bangladesh');
insert into regije (regija) values ('Netherlands');
insert into regije (regija) values ('South Africa');
insert into regije (regija) values ('China');
insert into regije (regija) values ('United States');
insert into regije (regija) values ('Ireland');
insert into regije (regija) values ('United States');
insert into regije (regija) values ('Indonesia');
insert into regije (regija) values ('China');
insert into regije (regija) values ('Japan');
